config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie_id, presence: true
  validates :list_id, presence: true
  validates_uniqueness_of :movie_id, scope: :list_id
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :find_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(require_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def find_list
    @list = List.find(params[:list_id])
  end

  def require_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :find_list, only: [:show]

  def index
    @lists = List.all
  end

  def show
    @movies = @list.movies
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(require_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def find_list
    @list = List.find(params[:id])
  end

  def require_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Yoo, select a 🐮vie to add to your <%= @list.name %> list</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie, label: 'Select movie', error: 'Please select a m🐮🐮vie ' %>
  <%= f.input :comment, label: 'Add a comment'%>
  <%= f.submit %>
<% end %>

<%= link_to "Back to lists", lists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Movie lists</h1>

<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list_path(list) %></li>
  <% end %>
</ul>

<%= link_to "Add new list", new_list_path %>

app/views/lists/new.html.erb
<h1>Hey! Create your new 🐮vie list here</h1>

<%= simple_form_for(@list) do |f| %>
  <%= f.input :name, label: 'List name', error: '🐮 Make me happy and fill it in' %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

<%= link_to "Back to lists", lists_path %>

app/views/lists/show.html.erb
<h1><%= @list.name %>'s 🐮vies list</h1>

<% if @list.photo.attached? %>
  <%= cl_image_tag @list.photo.key, height: 300, width: 400, crop: :fill %>
</div>
<% end %>

<ul>
  <% @movies.each do |movie| %>
    <li><%= movie.title %></li>
    <li><%= movie.overview %></li>
    <li><%= movie.rating %></li>
    <img src="<%= movie.poster_url %>"/>
    <p>   </p>
    <p>   </p>
  <% end %>
</ul>


<%= link_to "Back to lists", lists_path %>

<%= link_to "Add movie", new_list_bookmark_path(@list) %>